export const devData = [
  {
    src: "png/1718869237314.png",
    name: "Anubhav",
    designation: "Frontend Developer",
    desc: "A highly proficient front end developer dedicated to creating visually stunning and intuitive user interfaces. Expert in translating design into dynamic, responsive web experiences",
    skills: [
      "Leadership",
      "data engineer",
      "Decision Making",
      "React Js",
      "Planning",
      "Frontend",
      "Cloud",
    ],
    exp: "5+ years",
    availability: "Full-time",
  },
  {
    src: "png/1718803716559.webp",
    name: "Aditya",
    designation: "Frontend Developer",
    desc: "A highly proficient front end developer dedicated to creating visually stunning and intuitive user interfaces. Expert in translating design into dynamic, responsive web experiences",
    skills: [
      "Computer Science",
      "data engineer",
      "Decision Making",
      "React Js",
      "Planning",
      "Frontend",
      "Cloud",
    ],
    exp: "5+ years",
    availability: "Full-time",
  },
  {
    src: "png/1718803291888.webp",
    name: "Chetan",
    designation: "Backend Developer",
    desc: "A highly proficient front end developer dedicated to creating visually stunning and intuitive user interfaces. Expert in translating design into dynamic, responsive web experiences",
    skills: [
      "Computer Science",
      "data engineer",
      "Decision Making",
      "Node Js",
      "Planning",
      "Backend",
      "Cloud",
    ],
    exp: "7+ years",
    availability: "Full-time",
  },
  {
    src: "png/1718802984371.webp",
    name: "Rupali",
    designation: "Frontend Developer",
    desc: "A highly proficient front end developer dedicated to creating visually stunning and intuitive user interfaces. Expert in translating design into dynamic, responsive web experiences",
    skills: [
      "Computer Science",
      "data engineer",
      "Decision Making",
      "React Js",
      "Planning",
      "Frontend",
      "Cloud",
    ],
    exp: "3+ years",
    availability: "Full-time",
  },
  {
    src: "png/1718803548567.webp",
    name: "Abhishek",
    designation: "Frontend Developer",
    desc: "A highly proficient front end developer dedicated to creating visually stunning and intuitive user interfaces. Expert in translating design into dynamic, responsive web experiences",
    skills: [
      "Computer Science",
      "data engineer",
      "Decision Making",
      "React Js",
      "Planning",
      "Frontend",
      "Cloud",
    ],
    exp: "2.5+ years",
    availability: "Full-time",
  },
];
